//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.DetailsOfTravels = new HashSet<DetailsOfTravel>();
        }
    
        public int Id { get; set; }
        public string PersonId { get; set; }
        public Nullable<int> Car { get; set; }
        public Nullable<int> PreferenceId { get; set; }
    
        public virtual Car Car1 { get; set; }
        public virtual ICollection<DetailsOfTravel> DetailsOfTravels { get; set; }
        public virtual Person Person { get; set; }
        public virtual Preference Preference { get; set; }
    }
}
