//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joiner
    {
        private string idPassenger;
        private int idTravel;

        public Joiner()
        {
        }

        public Joiner(string idPassenger, int idTravel)
        {
            this.PassengerId = idPassenger;
            this.TravelId = idTravel;
        }

        public int Id { get; set; }
        public string PassengerId { get; set; }
        public int TravelId { get; set; }
    
        public virtual DetailsOfTravel DetailsOfTravel { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
