//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string idDriver { get; set; }
        public string idPassenger { get; set; }
        public string MessageText { get; set; }
        public System.DateTime Time { get; set; }
        public bool driverToPassenger { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Person Person { get; set; }
    }
}
