//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carDBEntities : DbContext
    {
        public carDBEntities()
            : base("name=carDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Cars { get; set; }
        public DbSet<DetailsOfTravel> DetailsOfTravels { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Joiner> Joiners { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Preference> Preferences { get; set; }
    }
}
