//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.Joiners = new HashSet<Joiner>();
            this.Messages = new HashSet<Message>();
        }
    
        public string PassengerId { get; set; }
    
        public virtual ICollection<Joiner> Joiners { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Person Person { get; set; }
    }
}
