//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Drivers = new HashSet<Driver>();
            this.Messages = new HashSet<Message>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
